language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

# faster builds on new travis setup not using sudo
sudo: false

install:
  - '[[ -z "$CI_USER_TOKEN" ]] || composer config github-oauth.github.com ${CI_USER_TOKEN};'
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --prefer-dist --no-interaction
  - 'php -S 127.0.0.1:8000 -t tests/data/app >/dev/null 2>&1 &'
  - 'php -S 127.0.0.1:8010 -t tests/data/rest >/dev/null 2>&1 &'

script:
  - php ./vendor/bin/codecept run
